version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "src/Pure.Collections.Generic"
    - "src/Tests/Pure.Collections.Generic.Tests"
  schedule:
    interval: daily
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
